logDir: "logs"
port: 3002

mongo:
  dbhost: "host"
  dbname: "dbname"
  dbuser: "dbuser"
  dbpassword: "dbpassword"

mysql:
  dbname: "test_mysql_bd"
  dbuser: "dbuser"
  dbpassword: "dbpassword"

rateLimiter:
  enabled: false
  # Bucket filling rate 
  rate: 2 
  # Token size of bucket
  burst: 4